# Generated by Django 4.1.5 on 2023-04-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Short Name")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active?"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Game name")),
                (
                    "pub_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Publication date"
                    ),
                ),
                ("release_date", models.DateField(verbose_name="Release date")),
                ("description", models.TextField(verbose_name="Game Description")),
                (
                    "game_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="game_image",
                        verbose_name="Game Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Short Name")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active?"),
                ),
                (
                    "team_name",
                    models.CharField(max_length=50, verbose_name="Team name"),
                ),
                ("description", models.TextField(verbose_name="Description Team")),
                ("create_date", models.DateField(verbose_name="Create date")),
                (
                    "team_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="team_logo",
                        verbose_name="Team Logo",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="gamenews.game",
                        verbose_name="Discipline ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Short Name")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active?"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last name"),
                ),
                ("nickname", models.CharField(max_length=50, verbose_name="Nickname")),
                (
                    "player_pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="player_pic",
                        verbose_name="Player pictures",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="Bio")),
                (
                    "team",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="gamenews.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
