# Generated by Django 4.1.5 on 2023-04-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamenews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="rating",
            field=models.IntegerField(null=True, verbose_name="Player rating"),
        ),
    ]
