# Generated by Django 4.1.5 on 2023-04-23 18:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gamenews", "0002_player_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Short Name")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active?"),
                ),
                ("title", models.CharField(max_length=120)),
                ("content", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                (
                    "post_pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="post_pic",
                        verbose_name="Post pictures",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
