# Generated by Django 4.1.5 on 2023-04-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamenews", "0003_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_pic",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to="post_pic",
                verbose_name="Post pictures",
            ),
        ),
    ]
