# Generated by Django 4.1.5 on 2023-04-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gamenews", "0007_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="game",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="gamenews.game",
                verbose_name="Discipline ",
            ),
        ),
    ]
