# Generated by Django 4.1.5 on 2023-05-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamenews", "0009_game_post_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="achievement",
            field=models.CharField(
                default=None, max_length=200,null=True, verbose_name="Achievement"
            ),
        ),
    ]
