# Generated by Django 4.1.5 on 2023-05-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamenews", "0010_player_achievement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_pic",
            field=models.ImageField(
                blank=True,
                default="default_post_picture.png",
                null=True,
                upload_to="post_pic",
                verbose_name="Post pictures",
            ),
        ),
    ]
