# Generated by Django 4.1.5 on 2023-04-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="users_pic"
            ),
        ),
    ]
