# Generated by Django 4.1.5 on 2023-05-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamenews", "0012_alter_team_game"),
        ("users", "0003_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="favourite",
            field=models.ManyToManyField(to="gamenews.post"),
        ),
    ]
